### ISSUE TITLE
Invalid get index <code> opening a .zip file

### ISSUE THREAD

**Issue by fenix-hub** [jellehermsen/gdunzip#4]
Hello,
I'm trying to unzip a .zip folder containing only two text files, an .md and a .txt.
When I try to extract files from it, an error prints in console:  
![error](https://user-images.githubusercontent.com/45271396/69907114-3ebdb700-13cf-11ea-8dcb-cf4e2549308c.PNG)  

Here it is the code:  
```
var unzipper = load("res://addons/github-integration/resources/extraction/gdunzip.gd").new()
[...]
func extraction_process():
	var archive = unzipper.load_archive(zip_filepath)
	var uncompressed_file : File = File.new()
	if archive:
		for file in unzipper.files:
			var uncompressed = unzipper.uncompress(file)
			if uncompressed:
				uncompressed_file.open("res://uncompressed/"+file,File.WRITE)
				uncompressed_file.store_string(uncompressed.get_string_from_utf8())
				uncompressed_file.close()
```

where `zip_filepath` is just the path to the zip I'm getting after a download.

And I'm attaching the zip too, if you need to test.

[my-br-app-linux.zip](https://github.com/jellehermsen/gdunzip/files/3907671/my-br-app-linux.zip)

Thank you very much for your support, waiting for your response, if you need anything more.

**Comment by jellehermsen** [comment]
I can replicate the bug. There seems to be a problem in the function that tries to retrieve the file information from the central directory inside the zip file. I will check and see if I can pinpoint it exactly and fix it.

**Comment by jellehermsen** [comment]
I have fixed the bug. It failed at trying to find the offset in the zip file of the central directory. You can checkout the latest version of the code and you should find that it works properly now.
