### ISSUE TITLE
Error when decompressing

### ISSUE THREAD

**Issue by Joanguitar** [jellehermsen/gdunzip#6]
Hi,

Thank you for this addon.

I'm having problems to uncompress the file "song.egg" from this [File](https://beatsaver.com/api/download/key/b)
It looks like the code gets stuck in an endless loop.

The code I'm using is:
```
	var gdunzip = load('res://addons/gdunzip/gdunzip.gd').new()
	var loaded = gdunzip.load(zip_file)
	var uncompressed = gdunzip.uncompress(fileName)
        return uncompressed
```
where
zip_file: is the path to the zip file
fileName: is "song.egg"

**Comment by jellehermsen** [comment]
I have checked it out and your zip file is a bit too complicated for gdunzip. I suspect it was made with a high amount of compression and it tried to compress song.egg. It's a 4mb ogg file however, so uncompressing it in plain GDScript is simply too much. There's also little to gain from compressing ogg files, so you might be better off creating the zip file without actually using compression. In linux you can do this on the commandline with:

`zip -r -0 newfile.zip *`

I have created a new test.zip using this command and was able to extract the file without issue:
[test.zip](https://github.com/jellehermsen/gdunzip/files/5245276/test.zip)
