### ISSUE TITLE
Not uncompressing a large file

### ISSUE THREAD

**Issue by Zarasan** [jellehermsen/gdunzip#9]
I am trying to extract a large file from a zip. But it gets stuck on it and doesn't continue. It goes through the other files but not that one.
[Tester.zip](https://github.com/jellehermsen/gdunzip/files/5384582/Tester.zip)

**Comment by jellehermsen** [comment]
Gdunzip seems to have issues uncompressing large files. You can circumvent this by using no compression for that file, using the zip as a mere container format. This issue is related to https://github.com/jellehermsen/gdunzip/issues/6
